name: dappunk
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^9.1.0
  
  # Audio Dependencies
  record: ^5.1.0
  just_audio: ^0.9.36
  ffmpeg_kit_flutter_new: ^4.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  audio_waveforms: ^1.0.5
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.2
  go_router: ^14.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

dependency_overrides:
  record_linux: ^1.0.0
